version: 2
vm_settings: &vm_settings
  working_directory: ~/project/webpack-template
  docker:
    - image: circleci/node:8.3-browsers

run_tests: &run_tests
  - checkout
  - attach-workspace:
      at: ~/project
  - run:
      name: roll out template
      command: .bin/vue init . test-$VUE_TEMPL_TEST
  - restore_cache:
          key: template-cache-{{ .Environment.VUE_TEMP_TEST }}-{{ checksum "test/package.json" }}
  - run:
      name: Install npm dependencies
      command: cd test && npm install
  - save_cache:
      key: template-cache-{{ .Environment.VUE_TEMP_TEST }}-{{ checksum "test/package.json" }}
      paths:
        - test-$VUE_TEMPL_TEST/node_modules

jobs:
  install_template_deps:
    <<: *vm_settings
    steps:
      - checkout
      - restore_cache:
          key: template-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: template-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - webpack-template/node_modules

  scenario_minimal:
    <<: *vm_settings
    environment:
      - VUE_TEMPL_TEST: minimal
    steps: *run_tests
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - install_template_deps
      - scenario_minimal:
          requires:
            - install_template_deps
      - scenario_full:
          requires:
            - install_template_deps
