version: 2
vm_settings: &vm_settings
  docker:
    - image: circleci/node:8.3-browsers

create_project: &create_project
  - checkout
  - attach-workspace:
      at: ~/project
  - run:
      name: run cli
      command: ../.bin/vue init . test-$VUE_TEMLP_TEST

run_unit_tests: &run_unit_tests
    steps:
      - checkout
      - attach_workspace:
            at: ~/project
      - run:
          name: Unit Tests
          command: npm run unit

run_e2e_tests: &run_e2e_tests
  steps:
    - checkout
    - attach_workspace:
          at: ~/project
    - run:
        name: End-To-End Tests
        command: npm run e2e

jobs:
  install_template_deps:
    <<: *vm_settings
    working_directory: ~/project/webpack-template
    steps:
      - checkout
      - restore_cache:
          key: template-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: template-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - webpack-template/node_modules

  create_minimal:
    <<: *vm_settings
    working_directory: ~/project/webpack-template
    environment:
      - VUE_TEMPL_TEST: minimal
    <<: *create_project
  
  unit_minimal:
    <<: *vm_settings
    working_directory: ~/project/webpack-template/test-minimal
    <<: *run_unit_tests

  e2e_minimal:
    <<: *vm_settings
    working_directory: ~/project/webpack-template/test-minimal
    <<: *run_e2e_tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_template_deps
      - create_project:
          requires:
            - install_template_deps
      - install_project_deps:
          requires:
            - create_project
      - run_unit_tests:
          requires:
            - install_project_deps
      - run_e2e_tests:
          requires:
            - install_project_deps
